version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3.9.12-management-alpine
    container_name: metis-core-rabbitmq
    environment:
      - RABBIT_DEFAULT_VHOST=/
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - '5672:5672'
      - '15672:15672'
  redis:
    image: redis:6.0.16-alpine
    container_name: metis-core-redis
    command: redis-server --requirepass guest
    ports:
      - '6379:6379'
  mongo:
    image: mongo:4.2.9
    container_name: metis-core-mongo
    environment:
      MONGO_INITDB_DATABASE: metis-core
      MONGO_INITDB_ROOT_USERNAME: guest
      MONGO_INITDB_ROOT_PASSWORD: guest
    ports:
      - '27017:27017'
  metis-core-local:
    image: europeana/metis-core:feat-MET-4984-dockerize-metis-core
    container_name: metis-core-local
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    environment:
      RABBITMQ_HOST: metis-core-rabbitmq
      MONGO_HOSTS: metis-core-mongo
      REDIS_HOST: metis-core-redis
    volumes:
      - /data/metis-configuration/metis-framework/metis-core/metis-core-rest/k8s/overlays/local/resources/custom-truststore.jks:/data/certificates/custom-truststore.jks
      - /data/metis-configuration/metis-framework/metis-core/metis-core-rest/k8s/overlays/local/resources/application.properties:/application.properties
      - /data/metis-configuration/metis-framework/metis-core/metis-core-rest/k8s/overlays/local/resources/log4j2.xml:/data/logging/log4j2.xml
    depends_on:
      - rabbitmq
      - mongo
      - redis
