version: '3.8'

services:
  metis-core-local:
    image: europeana/metis-core:develop
    container_name: metis-core
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    #uncomment this if an .env file is to be used instead of a application.properties.
    #    env_file:
    #      - /data/metis-properties/test/metis-core-rest/.metis-core-test.env
    volumes:
      - /data/certificates/ibm-ca-truststore.jks:/data/certificates/ibm-ca-truststore.jks
      - /data/metis-properties/test/metis-core-rest/application-test.properties:/application.properties
      - /data/logging/log4j2.xml:/log4j2.xml
