version: '3.8'

services:
  mongo:
    image: mongo:4.2.9
    container_name: metis-dereference-mongo
    environment:
      MONGO_INITDB_DATABASE: metis-dereference
      MONGO_INITDB_ROOT_USERNAME: guest
      MONGO_INITDB_ROOT_PASSWORD: guest
    ports:
      - '27017:27017'
  metis-dereference-local:
    image: europeana/metis-dereference:develop
    container_name: metis-dereference-local
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    environment:
      MONGO_HOSTS: metis-core-mongo
    volumes:
      - /data/metis-configuration/metis-framework/metis-dereference/metis-dereference-rest/k8s/overlays/local/components/properties/application.properties:/application.properties
      - /data/metis-configuration/k8s/custom-truststore-jks/custom-truststore.jks:/data/certificates/custom-truststore.jks
      - /data/metis-configuration/k8s/log4j2-xml/log4j2.xml:/data/logging/log4j2.xml
    depends_on:
      - mongo