version: '3.8'
services:
  mongo:
    image: mongo:4.2.9
    container_name: metis-repository-mongo
    environment:
      MONGO_INITDB_DATABASE: metis-repository
      MONGO_INITDB_ROOT_USERNAME: guest
      MONGO_INITDB_ROOT_PASSWORD: guest
    ports:
      - '27017:27017'
  metis-repository-local:
    image: europeana/metis-repository:develop
    container_name: metis-repository-local
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    environment:
      MONGO_HOSTS: metis-repository-mongo
    volumes:
      - /data/metis-configuration/metis-framework/metis-repository/metis-repository-rest/k8s/overlays/local/components/properties/application.properties:/application.properties
      - /data/metis-configuration/k8s/common-components/log4j2-xml/log4j2.xml:/data/logging/log4j2.xml
    depends_on:
      - mongo
