name: CI

on:
  push:
    #Do not run on main to avoid duplicate builds during release
    branches-ignore:
      - '!master'
      - '!main'
    #Run on release tags
    tags:
      - 'v*'

jobs:
  ci:
    uses: europeana/metis-actions/.github/workflows/ci.yml@main
    with:
      sonar_organization: europeana
      sonar_project_key: europeana_metis-framework
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
  deploy-artifacts:
    needs: ci
    uses: europeana/metis-actions/.github/workflows/deploy-artifacts.yml@main
    secrets:
      ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
      ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
  docker-build_metis-authentication:
    needs: ci
    uses: europeana/metis-actions/.github/workflows/docker-build-push.yml@main
    with:
      docker-organization: europeana
      docker-image-name: metis-authentication
      project-path: metis-authentication/metis-authentication-rest/
    secrets:
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
  docker-build_metis-core:
    needs: ci
    uses: europeana/metis-actions/.github/workflows/docker-build-push.yml@main
    with:
      docker-organization: europeana
      docker-image-name: metis-core
      project-path: metis-core/metis-core-rest/
    secrets:
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
  docker-build_metis-dereference:
    needs: ci
    uses: europeana/metis-actions/.github/workflows/docker-build-push.yml@main
    with:
      docker-organization: europeana
      docker-image-name: metis-dereference
      project-path: metis-dereference/metis-dereference-rest/
    secrets:
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
  docker-build_metis-repository:
    needs: ci
    uses: europeana/metis-actions/.github/workflows/docker-build-push.yml@main
    with:
      docker-organization: europeana
      docker-image-name: metis-repository
      project-path: metis-repository/metis-repository-rest/
    secrets:
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}