name: CI

on: push

jobs:

  ci:
    uses: europeana/metis-actions/.github/workflows/ci.yml@jdk21
    with:
      sonar_organization: europeana
      sonar_project_key: europeana_metis-framework
    secrets:
      SONAR_TOKEN: ${{ secrets.METIS_SONAR_TOKEN }}

  deploy-artifacts:
    needs: ci
    uses: europeana/metis-actions/.github/workflows/deploy-artifacts.yml@jdk21
    secrets:
      ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
      ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}

  docker-build_metis-authentication:
    needs: ci
    uses: europeana/metis-actions/.github/workflows/docker-build-push.yml@jdk21
    with:
      docker-organization: europeana
      docker-image-name: metis-authentication
      project-path: metis-authentication/metis-authentication-rest/
    secrets:
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
  docker-build_metis-core:
    needs: ci
    uses: europeana/metis-actions/.github/workflows/docker-build-push.yml@jdk21
    with:
      docker-organization: europeana
      docker-image-name: metis-core
      project-path: metis-core/metis-core-rest/
    secrets:
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
  docker-build_metis-dereference:
    needs: ci
    uses: europeana/metis-actions/.github/workflows/docker-build-push.yml@jdk21
    with:
      docker-organization: europeana
      docker-image-name: metis-dereference
      project-path: metis-dereference/metis-dereference-rest/
    secrets:
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
  docker-build_metis-repository:
    needs: ci
    uses: europeana/metis-actions/.github/workflows/docker-build-push.yml@jdk21
    with:
      docker-organization: europeana
      docker-image-name: metis-repository
      project-path: metis-repository/metis-repository-rest/
    secrets:
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}