name: CI

on:
  push:
    #Do not run on main to avoid duplicate builds during release
    branches-ignore:
      - '!master'
      - '!main'
    #Run on release tags
    tags:
      - 'v*'

jobs:
  ci:
    uses: europeana/metis-actions/.github/workflows/ci.yml@main
    with:
      sonar_organization: europeana
      sonar_project_key: europeana_metis-framework
    secrets: inherit
  docker-build_metis-authentication:
    needs: ci
    uses: europeana/metis-actions/.github/workflows/docker-build-push.yml@main
    with:
      docker-organization: europeana
      docker-image-name: metis-authentication
      project-path: metis-authentication/metis-authentication-rest/
    secrets: inherit
  docker-build_metis-core:
    needs: ci
    uses: europeana/metis-actions/.github/workflows/docker-build-push.yml@main
    with:
      docker-organization: europeana
      docker-image-name: metis-core
      project-path: metis-core/metis-core-rest/
    secrets: inherit
  docker-build_metis-dereference:
    needs: ci
    uses: europeana/metis-actions/.github/workflows/docker-build-push.yml@main
    with:
      docker-organization: europeana
      docker-image-name: metis-dereference
      project-path: metis-dereference/metis-dereference-rest/
    secrets: inherit